name: Feature Request
description: Tell about a feature you think nvim-snippy is missing
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a probleam? Please describe.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Ideas or possible solutions
      description: Share your ideas about potential solutions
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you have considered
      description: Alternative solutions or features you've considered.
    validations:
      required: false
