name: CI
on:
  push:
    branches: 'master'
  pull_request:
    branches: 'master'

jobs:
  linux:
    strategy:
      matrix:
        version: [stable, nightly]

    runs-on: ubuntu-latest

    steps:

      - name: Setup neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.version }}

      - name: Set nvim version
        id: vars
        run: |
          echo "::set-output name=nvim_ref::$(nvim --version | head -1 | cut -d' ' -f2)"

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: neovim
          key: ${{ runner.os }}-nvim-${{ steps.vars.outputs.nvim_ref }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake build-essential cmake gcc-11 gettext gperf libtool-bin locales ninja-build pkg-config unzip

      - name: Setup lua
        uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: "luajit"

      - name: Setup luarocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Setup vusted
        run: |
          luarocks install vusted

      - name: Run unit tests
        run: |
          make unittest

      - name: Run functional tests
        env:
          NEOVIM_BRANCH: ${{ matrix.version }}
        run: |
          make functionaltest
